# S3c24XX Platform Support
snd-soc-s3c24xx-objs := s3c-dma.o
snd-soc-lpam-objs := lpam-dma.o
snd-soc-s3c24xx-i2s-objs := s3c24xx-i2s.o
snd-soc-s3c2412-i2s-objs := s3c2412-i2s.o
snd-soc-s5p-i2s-objs := s5p-i2s.o
snd-soc-s5p-i2s-lp-objs := s5p-i2s-lp.o
snd-soc-s3c2443-ac97-objs := s3c2443-ac97.o
snd-soc-s5p-ac97-objs := s5p-ac97.o
snd-soc-s3c-i2s-v2-objs := odroid-i2s-bus1.o
snd-soc-s3c-pcm-objs := s3c-pcm.o
snd-soc-s5p-spdif-objs := s5p-spdif.o
snd-soc-oeroid-i2s-bus1-objs := odroid-i2s-bus1.o
snd-soc-odroid-spdif-objs := odroid-s5p-spdif.o

obj-$(CONFIG_SND_S3C24XX_SOC) += snd-soc-s3c24xx.o
obj-$(CONFIG_SND_LPAM_SOC) += snd-soc-lpam.o
obj-$(CONFIG_SND_S3C24XX_SOC_I2S) += snd-soc-s3c24xx-i2s.o
obj-$(CONFIG_SND_S3C2443_SOC_AC97) += snd-soc-s3c2443-ac97.o
obj-$(CONFIG_SND_S3C2412_SOC_I2S) += snd-soc-s3c2412-i2s.o
obj-$(CONFIG_SND_S5P_SOC_I2S) += snd-soc-s5p-i2s.o
obj-$(CONFIG_SND_S5P_SOC_I2S_LP) += snd-soc-s5p-i2s-lp.o
obj-$(CONFIG_SND_S5P_SOC_AC97) += snd-soc-s5p-ac97.o
obj-$(CONFIG_SND_S3C_I2SV2_SOC) += snd-soc-oeroid-i2s-bus1.o
obj-$(CONFIG_SND_S3C_SOC_PCM) += snd-soc-s3c-pcm.o
obj-$(CONFIG_SND_S5P_SPDIF) += snd-soc-s5p-spdif.o
obj-$(CONFIG_SND_ODROID_SPDIF) += snd-soc-odroid-spdif.o

# S3C24XX Machine Support
snd-soc-neo1973-wm8753-objs := neo1973_wm8753.o
snd-soc-smdk2443-wm9710-objs := smdk2443_wm9710.o
snd-soc-ln2440sbc-alc650-objs := ln2440sbc_alc650.o
snd-soc-s3c24xx-uda134x-objs := s3c24xx_uda134x.o
snd-soc-smdks5p-wm8580-objs := smdks5p_wm8580.o
snd-soc-smdks5plp-wm8580-objs := smdks5plp_wm8580.o
snd-soc-smdks5p-wm9713-objs := smdks5p_wm9713.o
snd-soc-universal-ak4671-objs := universal_ak4671.o
snd-soc-smdks5p-spdif-objs := smdks5p_hdmi_spdif.o

snd-soc-odroid-wm8991-objs := odroid-s5p-wm8991.o

obj-$(CONFIG_SND_S3C24XX_SOC_NEO1973_WM8753) += snd-soc-neo1973-wm8753.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2443_WM9710) += snd-soc-smdk2443-wm9710.o
obj-$(CONFIG_SND_S3C24XX_SOC_LN2440SBC_ALC650) += snd-soc-ln2440sbc-alc650.o
obj-$(CONFIG_SND_S3C24XX_SOC_S3C24XX_UDA134X) += snd-soc-s3c24xx-uda134x.o
obj-$(CONFIG_SND_S5P_SOC_WM8580) += snd-soc-smdks5p-wm8580.o
obj-$(CONFIG_SND_S5P_SOC_WM8580_LP) += snd-soc-smdks5plp-wm8580.o
obj-$(CONFIG_SND_S5P_SOC_SMDK_WM9713) += snd-soc-smdks5p-wm9713.o
obj-$(CONFIG_SND_S5PC100_SOC_UNIVERSAL_AK4671) += snd-soc-universal-ak4671.o
obj-$(CONFIG_SND_SMDKS5P_HDMI_SPDIF) += snd-soc-smdks5p-spdif.o

obj-$(CONFIG_SND_S5P_SOC_WM8991) += snd-soc-odroid-wm8991.o
#obj-$(CONFIG_SND_S5P_SOC_WM8991) += snd-soc-odroid-spdif.o
